# Generated by Django 4.2 on 2023-04-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created_time', models.DateField(default='06-04-23')),
                ('due_time', models.DateField(default='06-04-23')),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='Tasker.category')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
