# Generated by Django 4.1.7 on 2023-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_linkmapping_delete_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmapping',
            name='id',
        ),
        migrations.AlterField(
            model_name='linkmapping',
            name='original_url',
            field=models.CharField(max_length=256, primary_key=True, serialize=False),
        ),
    ]
